from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait as wait
from decouple import config
import logging
import time
import pyautogui

logging.basicConfig(level=logging.DEBUG,
                    filename="contido.log", 
                    format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
                    datefmt='%m-%d %H:%M',
                    filemode='a+') 
console = logging.StreamHandler()
console.setLevel(logging.INFO)
#console.setLevel(logging.DEBUG)
formatter = logging.Formatter(fmt='%(asctime)s %(levelname)-8s %(message)s',datefmt='%Y-%m-%d %H:%M:%S')
console.setFormatter(formatter)
logging.getLogger('').addHandler(console)
logger_login= logging.getLogger('scontido_add_show.py')


try:
	URL_PATH = config('URL')
	wait_time= 1
	#driver= webdriver.Firefox(executable_path='/usr/bin/geckodriver')
	driver = webdriver.Chrome()
	driver.implicitly_wait(4)
	driver.maximize_window()
	actions = ActionChains(driver)
	driver.get(URL_PATH)
	logger_login.info("Connection created successfully")
	''' login '''
	username = driver.find_element_by_xpath('/html/body/div[1]/div/div/div[2]/div/div[1]/div/div/div/form/div[1]/input')
	username.clear()
	username.send_keys(config('user2'))
	time.sleep(2)
	password = driver.find_element_by_xpath('/html/body/div[1]/div/div/div[2]/div/div[1]/div/div/div/form/div[2]/input')
	password.clear()
	password.send_keys(config('user2_password'))
	time.sleep(2)
	driver.save_screenshot("test9Oct2019_l.png")
	login= driver.find_element_by_xpath('/html/body/div[1]/div/div/div[2]/div/div[1]/div/div/button')
	login.click()
	time.sleep(4)
	logger_login.info("login successfully")
	''' select onboard '''
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Control']"))).click()
	time.sleep(wait_time)
	driver.find_element_by_xpath('//*[@id="root"]/div/div[1]/div[1]/div/div[1]/div[3]/a[2]/div')
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//a[text()='Onboard']"))).click()
	time.sleep(wait_time)
	''' Basic info '''
	show_name = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[1]/div/div[2]/div[2]/div/div[1]/div/div/div/div/input')
	show_name.clear()
	show_name.send_keys(config('show_name'))
	time.sleep(wait_time)
	season_name = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[1]/div/div[2]/div[2]/div/div[2]/div/div/div/div/input')
	season_name.clear()
	season_name.send_keys(config('season_name'))
	time.sleep(wait_time)
	number_of_episodes = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[1]/div/div[2]/div[2]/div/div[3]/div[2]/div/div/div/input')
	number_of_episodes.clear()
	number_of_episodes.send_keys('40')
	time.sleep(wait_time)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Hindi']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Telugu']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Tamil']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Kannada']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Malayalam']"))).click()
	time.sleep(wait_time)
	driver.save_screenshot("test9Oct2019_2.png")
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Next']"))).click()
	time.sleep(wait_time)
	logger_login.info("Basic info added successfully")
	''' Schedule info '''
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Asianet']"))).click()
	time.sleep(wait_time)
	driver.find_element_by_xpath("//div[@class='sc-hmzhuo hXCotp ardp-date-picker']").click()
	time.sleep(wait_time)
	month_header= driver.find_element_by_xpath("//div[@class='month-header']")
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='August']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='2020']"))).click()
	logger_login.info('month header selected')
	week_header= driver.find_element_by_xpath("//div[@class='week-header']")
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Fri']"))).click()
	logger_login.info('week header selected')
	weeks= driver.find_element_by_xpath("//div[@class='weeks']")
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='28']"))).click()
	logger_login.info('weeks selected')
	tx_time= driver.find_element_by_xpath("//div[@class='picker-holder']")
	hour_box= driver.find_element_by_xpath("//div[@class='hour-box']")
	for hour_data in range(6):
		up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	logger_login.info('Hour selected')	
	seperator_box= driver.find_element_by_xpath("//div[@class='separator-box']")
	time.sleep(wait_time)
	for minute_data in range(8):
		up_arrow2= driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/div[1]/div[2]/div/div/div[2]/div[3]/div[1]").click()
	time.sleep(wait_time)
	logger_login.info('Minute selected')
	time.sleep(1)
	pyautogui.moveTo(1050, 580)
	time.sleep(2)
	pyautogui.click(1050, 580)
	''' Select duration '''
	## <div class="sc-kLIISr jKlCGX"><div class="label-text">Tx Schedule</div><table class="holder-box"><tr class="list-row"><td class="list-cell label"><div>Mon</div></td><td class="list-cell input"><div class="sc-bsbRJL iolmbl"><div class="sc-esOvli bjCMAT searchable-section" style="cursor: text;"><p class="dropdown-label">Select Duration</p><input type="text" class="sc-iuJeZd bHQUGe" value="" style="visibility: hidden;"></div></div></td></tr><tr class="list-row"><td class="list-cell label"><div>Tue</div></td><td class="list-cell input"><div class="sc-bsbRJL iolmbl"><div class="sc-esOvli bjCMAT searchable-section" style="cursor: text;"><p class="dropdown-label">Select Duration</p><input type="text" class="sc-iuJeZd bHQUGe" value="" style="visibility: hidden;"></div></div></td></tr><tr class="list-row"><td class="list-cell label"><div>Wed</div></td><td class="list-cell input"><div class="sc-bsbRJL iolmbl"><div class="sc-esOvli bjCMAT searchable-section" style="cursor: text;"><p class="dropdown-label">Select Duration</p><input type="text" class="sc-iuJeZd bHQUGe" value="" style="visibility: hidden;"></div></div></td></tr><tr class="list-row"><td class="list-cell label"><div>Thu</div></td><td class="list-cell input"><div class="sc-bsbRJL iolmbl"><div class="sc-esOvli bjCMAT searchable-section" style="cursor: text;"><p class="dropdown-label">Select Duration</p><input type="text" class="sc-iuJeZd bHQUGe" value="" style="visibility: hidden;"></div></div></td></tr><tr class="list-row"><td class="list-cell label"><div>Fri</div></td><td class="list-cell input"><div class="sc-bsbRJL iolmbl"><div class="sc-esOvli bjCMAT searchable-section" style="cursor: text;"><p class="dropdown-label">Select Duration</p><input type="text" class="sc-iuJeZd bHQUGe" value="" style="visibility: hidden;"></div></div></td></tr><tr class="list-row"><td class="list-cell label"><div>Sat</div></td><td class="list-cell input"><div class="sc-bsbRJL iolmbl"><div class="sc-esOvli bjCMAT searchable-section" style="cursor: text;"><p class="dropdown-label">Select Duration</p><input type="text" class="sc-iuJeZd bHQUGe" value="" style="visibility: hidden;"></div></div></td></tr><tr class="list-row"><td class="list-cell label"><div>Sun</div></td><td class="list-cell input"><div class="sc-bsbRJL iolmbl"><div class="sc-esOvli bjCMAT searchable-section" style="cursor: text;"><p class="dropdown-label">Select Duration</p><input type="text" class="sc-iuJeZd bHQUGe" value="" style="visibility: hidden;"></div></div></td></tr></table></div> 
	##driver.find_element_by_xpath("//div[@class='sc-kLIISr jKlCGX']")
	#driver.find_element_by_xpath("//div[@class='sc-bsbRJL iolmbl']")
	#print('1')
	## //*[@id="root"]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/table/tr[1]/td[2]/div/div/input
	#tx_schedule1= driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/table/tr[1]/td[2]/div/div/input')
	#print('34')
	#tx_schedule1.click()
	#print('2')
	#time.sleep(wait_time)
	wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='5 mins']"))).click()
	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#tx_schedule= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[1]/div/div[2]/div/div/div/table/tr[2]/td[2]/div/div/input')
	#tx_schedule.click()
	##time.sleep(wait_time)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='20 mins']"))).click()
	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#tx_schedule= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[1]/div/div[2]/div/div/div/table/tr[3]/td[2]/div/div/input')
	#tx_schedule.click()
	##time.sleep(wait_time)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='10 mins']"))).click()
	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#tx_schedule= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[1]/div/div[2]/div/div/div/table/tr[4]/td[2]/div/div/input')
	#tx_schedule.click()
	#time.sleep(wait_time)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='15 mins']"))).click()
	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#tx_schedule= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[1]/div/div[2]/div/div/div/table/tr[5]/td[2]/div/div/input')
	#tx_schedule.click()
	##time.sleep(wait_time)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='60 mins']"))).click()
	#driver.save_screenshot("test9Oct2019_3.png")	
	#row_div=wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, ".//span[@class = 'tab-title']")))
	#row_div.click()
	#driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[1]/input").click()
	#print('program start date clicked')
	#month_header= driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[2]/div[1]")
	#print('month')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[2]/div[1]/span[2]/span[1]').click()
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[2]/div[1]/span[2]/span[2]').click()
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[2]/div[2]')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[2]/div[2]/span[4]').click()
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[2]/div[3]/div[1]/div[1]')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[2]/div[3]/div[1]/div[1]/div[4]/span').click()
	##time.sleep(6)
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]/div[1]')
	#for hour_button in range(4):
	#	driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]/div[1]/div[1]').click()
	#print('Hour selected')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]/div[2]')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]/div[3]')
	#for minute_button in range(5): 
	#	driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]/div[3]/div[1]').click()
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/table/tr[1]/td[2]/div')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/table/tr[1]/td[2]/div/div/input').click()
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/table/tr[1]/td[2]/div/div/p[2]').click()
	#
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/table/tr[2]/td[2]/div')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/table/tr[2]/td[2]/div/div/input').click()
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/table/tr[2]/td[2]/div/div/p[2]').click()
	##driver.find_element_by_xpath("//div[@class='sc-jVODtj gKQkJS']")
	#tx_time= driver.find_element_by_xpath("//div[@class='picker-holder']")
	#hour_box= driver.find_element_by_xpath("//div[@class='hour-box']")
	#up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#time.sleep(wait_time)
	#print('Hour selected')	
	#seperator_box= driver.find_element_by_xpath("//div[@class='separator-box']")
	#time.sleep(wait_time)
	##tx_time_minute= driver.find_element_by_xpath("//div[@class='picker-holder']")
	#minute_box= driver.find_element_by_xpath("//div[@class='minute-box']")
	#up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#time.sleep(wait_time)
	#print('Minute selected')
	##<div class="meridiem-box"><div>pm</div></div>
	#meridiem_box= driver.find_element_by_xpath("//div[@class='meridiem-box']")
	#time.sleep(1)	
	#wait(driver, 2).until(EC.element_to_be_clickable((By.XPATH, "//div[text()='pm']"))).click()  # converted into pm
	#time.sleep(wait_time)
	##print('meridiem-box selected')
	##time.sleep(2) 
	##<div class="sc-jeCdPy jzIkFw"><div class="sc-ePZHVD hUgaId searchable-section" style="cursor: text;"><p class="dropdown-label"></p><input type="text" class="sc-bEjcJn gONHtD" value=""></div></div>
	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#time.sleep(1)
	#print('1')
	#tx_schedule= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/table/tr[1]/td[2]/div/div/input')
	#tx_schedule.click()
	#print('2')
	##time.sleep(wait_time)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='30 mins']"))).click()

	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#tx_schedule= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[1]/div/div[2]/div/div/div/table/tr[2]/td[2]/div/div/input')
	#tx_schedule.click()
	##time.sleep(wait_time)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='20 mins']"))).click()

	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#tx_schedule= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[1]/div/div[2]/div/div/div/table/tr[3]/td[2]/div/div/input')
	#tx_schedule.click()
	##time.sleep(wait_time)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='10 mins']"))).click()

	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#tx_schedule= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[1]/div/div[2]/div/div/div/table/tr[4]/td[2]/div/div/input')
	#tx_schedule.click()
	##time.sleep(wait_time)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='15 mins']"))).click()

	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#tx_schedule= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[1]/div/div[2]/div/div/div/table/tr[5]/td[2]/div/div/input')
	#tx_schedule.click()
	##time.sleep(wait_time)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='60 mins']"))).click()

	#time.sleep(6)
	#print('asianet hd selected')

	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='NEXT']"))).click()
	logger_login.info("Schedule info added successfully")
	time.sleep(wait_time) 
	''' OTT Info details '''
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Hotstar']"))).click()
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Youtube']"))).click()
	#hotstar_show_name = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[1]/div/div/div/div/input')
	#hotstar_show_name.clear()
	#hotstar_show_name.send_keys('Man he bavare')
	#hotstar_show_ID = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[2]/div[1]/div/div/div/input')
	#hotstar_show_ID.clear()
	#hotstar_show_ID.send_keys('1005')
	#hotstar_season_ID = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[2]/div[2]/div/div/div/input')
	#hotstar_season_ID.clear()
	#hotstar_season_ID.send_keys('2005')
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Premium']"))).click()
	#time.sleep(1)
	##<div class="label-text">First Publish Time</div>

	#driver.find_element_by_xpath("//div[@class='row-div']")
	#tx_time= driver.find_element_by_xpath("//div[@class='picker-holder']")
	#hour_box= driver.find_element_by_xpath("//div[@class='hour-box']")
	#up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#time.sleep(wait_time)
	#minute_box= driver.find_element_by_xpath("//div[@class='minute-box']")
	#up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#meridiem_box= driver.find_element_by_xpath("//div[@class='meridiem-box']")
	#wait(driver, 2).until(EC.element_to_be_clickable((By.XPATH, "//div[text()='pm']"))).click()
	#time.sleep(wait_time)
	##/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[2]/div[1]/div/div/div/input
	##wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Youtube']"))).click()
	##wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Hotstar']"))).click()
	##time.sleep(wait_time)
	##driver.close()
	##driver.quit()
	#hotstar_first_publish_datediff = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[5]/div[1]/div/div/div/input')
	#hotstar_first_publish_datediff.clear()
	#hotstar_first_publish_datediff.send_keys('1')
	#hotstar_second_publish_datediff = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[5]/div[2]/div/div/div/input')
	#hotstar_second_publish_datediff.clear()
	#hotstar_second_publish_datediff.send_keys('1')
	##/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[6]/div[1]/div/div/div/input
	#hotstar_season_no=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[6]/div[1]/div/div/div/input')
	#hotstar_season_no.clear()
	#hotstar_season_no.send_keys('1')
	#hotstar_series_no=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[6]/div[2]/div/div/div/input')
	#hotstar_series_no.clear()
	#hotstar_series_no.send_keys('1')
	#hotstar_category_ID=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[7]/div[1]/div/div/div/input')
	#hotstar_category_ID.clear()
	#hotstar_category_ID.send_keys('100')
	#hotstar_productio_house=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[7]/div[2]/div/div/div/input')
	#hotstar_productio_house.clear()
	#hotstar_productio_house.send_keys('Endemol')
	#hotstar_dis_s3path=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[8]/div[1]/div/div/div/input')
	#hotstar_dis_s3path.clear()
	#hotstar_dis_s3path.send_keys('https://www.google.com')
	##/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[8]/div[2]/div/div/div/input
	#hotstar_dis_duration=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[8]/div[2]/div/div/div/input')
	#hotstar_dis_duration.clear()
	#hotstar_dis_duration.send_keys('30')
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Green']"))).click()
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Yellow']"))).click()
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Red']"))).click()
	#driver.save_screenshot("test9Oct2019_4.png")
	#time.sleep(4)
	#youtube_header=wait(driver, 5).until(EC.element_to_be_clickable((By.XPATH, ".//span[@class = 'tab-title']")))
	#youtube_header.click()
	##time.sleep(6)
	#youtube_show_name = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[1]/div/div/div/div/input')
	#youtube_show_name.clear()
	#youtube_show_name.send_keys('Hava ka zoka')
	#youtube_show_ID = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[2]/div[1]/div/div/div/input')
	#youtube_show_ID.clear()
	#youtube_show_ID.send_keys('1001')
	#youtube_season_ID = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[2]/div[2]/div/div/div/input')
	#youtube_season_ID.clear()
	#youtube_season_ID.send_keys('2001')
	##wait(driver, 5).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='SVOD']"))).click()
	##time.sleep(1)
	#publish_type1= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[3]/div/div/div/div[2]/label[2]/span')
	#publish_type1.click()
	#
	##print('SVOD')
	##wait(driver, 5).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Premium']"))).click()
	##time.sleep(1)
	##print('Premium')
	##<div class="label-text">First Publish Time</div>
	##driver.find_element_by_xpath("//div[@class='row-div']")
	##tx_time= driver.find_element_by_xpath("//div[@class='picker-holder']")
	##hour_box= driver.find_element_by_xpath("//div[@class='hour-box']")
	##up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	##up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	##up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	##time.sleep(wait_time)
	##minute_box= driver.find_element_by_xpath("//div[@class='minute-box']")
	##up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	##up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	##up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	##meridiem_box= driver.find_element_by_xpath("//div[@class='meridiem-box']")
	##wait(driver, 2).until(EC.element_to_be_clickable((By.XPATH, "//div[text()='pm']"))).click()
	##time.sleep(wait_time)
	##/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[2]/div[1]/div/div/div/input
	##wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Youtube']"))).click()
	##wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Hotstar']"))).click()
	##time.sleep(wait_time)
	##driver.close()
	##driver.quit()
	#youtube_first_publish_datediff = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[5]/div[1]/div/div/div/input')
	#youtube_first_publish_datediff.clear()
	#youtube_first_publish_datediff.send_keys('1')
	#youtube_second_publish_datediff = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[5]/div[2]/div/div/div/input')
	#youtube_second_publish_datediff.clear()
	#youtube_second_publish_datediff.send_keys('1')
	##/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[6]/div[1]/div/div/div/input
	##time.sleep(4)
	#print('publish date')
	#youtube_season_no=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[6]/div[1]/div/div/div/input')
	#youtube_season_no.clear()
	#youtube_season_no.send_keys('1')
	##time.sleep(4)
	#print('publish season')
	#youtube_series_no=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[6]/div[2]/div/div/div/input')
	#youtube_series_no.clear()
	#youtube_series_no.send_keys('1')
	##time.sleep(4)
	#print('publish series')
	#youtube_category_ID=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[7]/div[1]/div/div/div/input')
	#youtube_category_ID.clear()
	#youtube_category_ID.send_keys('100')
	##time.sleep(4)
	#print('category id')
	#youtube_productio_house=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[7]/div[2]/div/div/div/input')
	#youtube_productio_house.clear()
	#youtube_productio_house.send_keys('Endemol')
	##time.sleep(4)
	#print('production house')
	#youtube_dis_s3path=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[8]/div[1]/div/div/div/input')
	#youtube_dis_s3path.clear()
	#youtube_dis_s3path.send_keys('https://www.google.com')
	##/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[8]/div[2]/div/div/div/input
	#youtube_dis_duration=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[8]/div[2]/div/div/div/input')
	#youtube_dis_duration.clear()
	#youtube_dis_duration.send_keys('30')
	##time.sleep(12)
	#parental_rating2= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[10]/div/div/div/div[2]/label[2]/span')
	#parental_rating2.click()
	#print('yellow')
	#time.sleep(wait_time)
	##wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Yellow']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='NEXT']"))).click()
	logger_login.info("OTT info skipped successfully")
	''' Global Info '''
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='rural']"))).click()
	time.sleep(wait_time)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='non-fiction']"))).click()
	time.sleep(wait_time)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='politics']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='sports']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='business']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='health']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='literature']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='science']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='telecom']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='budget']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='festival']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='energy']"))).click()
	time.sleep(wait_time)
	driver.save_screenshot("test9Oct2019_5.png")
	logger_login.info(" global info added successfully")
	''' Global info task '''
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Ingest']"))).click()
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='S&P Cuts']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='S&P Review']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='PGM Review']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Subtitle']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Automatic Quality Check (AQC)']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Manual Quality Check (MQC)']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Dubbing']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Sharing']"))).click()
	time.sleep(1)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Disaster']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Tagging']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='OTT']"))).click()
	time.sleep(1)
	logger_login.info(" global info task added successfully")
	short_synopsis = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div/div[2]/div[2]/div/div[1]/div/div/div/div/div[2]/div/div[5]/div/div/div/div/input')
	short_synopsis.clear()
	short_synopsis.send_keys('Some of these stories are very short and basic.')	
	long_synopsis = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div/div[2]/div[2]/div/div[1]/div/div/div/div/div[2]/div/div[6]/div/div/div/div/input')
	long_synopsis.clear()
	long_synopsis.send_keys('The longer he lived, the more bile he was becoming and the more')
	time.sleep(wait_time)
	logger_login.info('short and long synopsis added')
	driver.save_screenshot("ttest9Oct2019_6.png")
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Add New Row']"))).click()
	credit1 = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div/div[2]/div[2]/div/div[1]/div/div/div/div/div[2]/div/div[7]/div/div/div/div/div[2]/table/tr/td[1]/div/div/input')
	credit1.clear()
	credit1.send_keys('shahrukh khan')
	credit2 = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div/div[2]/div[2]/div/div[1]/div/div/div/div/div[2]/div/div[7]/div/div/div/div/div[2]/table/tr/td[2]/div/div/input')
	credit2.clear()
	credit2.send_keys('actor')
	# Image upload
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='IMAGE UPLOAD']"))).click()
	#print('1')
	#web_banner= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div/div[2]/div[2]/div/div[1]/div/div/div/div/div[2]/div/div[1]/div/div/div/div/div[2]/div[2]/button').click()
	#print('2')
	#/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div/div[2]/div[2]/div/div[1]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/button
	#web_banner.click()
	#print('3')
	#time.sleep(8)
	
	add_show= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div/div[2]/div[2]/div/div[2]/div/div/div/div/button')
	#add_show.click()
	logger_login.info('Show added successfully')
	#time.sleep(2)
	#logout_icon= driver.find_element_by_xpath("//div[@class='header-profile']")
	#logout_icon.click()
	#time.sleep(2)
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//div[text()='Logout']"))).click()
	#time.sleep(2)
	#print('logout')
	time.sleep(4)
	search_onboard_show = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[1]/div[1]/input')
	search_onboard_show.clear()
	search_onboard_show.send_keys('IPL League')
	logger_login.info('search show completed')
	time.sleep(3)
	search_click_show=driver.find_element_by_xpath("//div[@class='search-list-item']")
	search_click_show.click()
	logger_login.info('search show done')
	time.sleep(3)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Next']"))).click()
	time.sleep(wait_time)
	logger_login.info("Basic info updated successfully")
	''' Schedule info '''
	time.sleep(wait_time)
	driver.find_element_by_xpath("//div[@class='sc-hmzhuo hXCotp ardp-date-picker']").click()
	time.sleep(wait_time)
	month_header= driver.find_element_by_xpath("//div[@class='month-header']")
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='September']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='2020']"))).click()
	logger_login.info('month header selected')
	week_header= driver.find_element_by_xpath("//div[@class='week-header']")
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Thu']"))).click()
	logger_login.info('week header selected')
	weeks= driver.find_element_by_xpath("//div[@class='weeks']")
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='3']"))).click()
	logger_login.info('weeks selected')
	tx_time= driver.find_element_by_xpath("//div[@class='picker-holder']")
	hour_box= driver.find_element_by_xpath("//div[@class='hour-box']")
	for hour_data in range(6):
		up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	logger_login.info('Hour selected')	
	seperator_box= driver.find_element_by_xpath("//div[@class='separator-box']")
	time.sleep(wait_time)
	for minute_data in range(8):
		up_arrow2= driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/div[1]/div[2]/div/div/div[2]/div[3]/div[1]").click()
	time.sleep(wait_time)
	logger_login.info('Minute selected')
	time.sleep(2)
	pyautogui.moveTo(1050, 580)
	time.sleep(2)
	pyautogui.click(1050, 580)
	wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='5 mins']"))).click()
	time.sleep(2)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='NEXT']"))).click()
	logger_login.info("Schedule info updated successfully")
	time.sleep(wait_time) 
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='NEXT']"))).click()
	logger_login.info("OTT info skipped successfully")
	
	''' update show '''
	update_show = driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div/div[2]/div[2]/div/div[2]/div/div/div/div/button')
	#update_show.click()
	logger_login.info('Show updated successfully')

	driver.close()
	driver.quit()

except Exception as e:
	logger_login.debug("Failed to connect internet: %s" %e)
	time.sleep(3)
	driver.close()
	driver.quit()


