from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait as wait
from decouple import config
import logging
import time
import pyautogui

logging.basicConfig(level=logging.DEBUG,
                    filename="contido.log", 
                    format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
                    datefmt='%m-%d %H:%M',
                    filemode='a+') 
console = logging.StreamHandler()
console.setLevel(logging.INFO)
#console.setLevel(logging.DEBUG)
formatter = logging.Formatter(fmt='%(asctime)s %(levelname)-8s %(message)s',datefmt='%Y-%m-%d %H:%M:%S')
console.setFormatter(formatter)
logging.getLogger('').addHandler(console)
logger_season= logging.getLogger('scontido_add_season.py')
driver = webdriver.Chrome()

try:
	URL_PATH = config('URL')
	wait_time= 1
	#driver= webdriver.Firefox(executable_path='/usr/bin/geckodriver')
	driver.implicitly_wait(1)
	driver.maximize_window()
	actions = ActionChains(driver)
	driver.get(URL_PATH)
	logger_season.info("Connection created successfully")
	''' login '''
	username = driver.find_element_by_xpath('/html/body/div[1]/div/div/div[2]/div/div[1]/div/div/div/form/div[1]/input')
	username.clear()
	username.send_keys(config('operation_user'))
	time.sleep(2)
	password = driver.find_element_by_xpath('/html/body/div[1]/div/div/div[2]/div/div[1]/div/div/div/form/div[2]/input')
	password.clear()
	password.send_keys(config('operation_password'))
	time.sleep(2)
	''' close chat box '''
	pyautogui.moveTo(1345, 670,duration=2)
	pyautogui.click(1345, 670)
	pyautogui.moveTo(1325, 430,duration=2)
	pyautogui.click(1325, 430)
	time.sleep(2)
	login= driver.find_element_by_xpath('/html/body/div[1]/div/div/div[2]/div/div[1]/div/div/button')
	login.click()
	time.sleep(4)

	logger_season.info("login successfully")
	''' select onboard '''
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Control']"))).click()
	time.sleep(wait_time)
	driver.find_element_by_xpath('//*[@id="root"]/div/div[1]/div[1]/div/div[1]/div[3]/a[2]/div')
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//a[text()='Onboard']"))).click()
	time.sleep(wait_time)
	''' select season'''
	season_button= driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/div[1]/div[2]/div/div[1]/a[2]')
	season_button.click()
	logger_season.info('season tab selected')
	time.sleep(4)
	showname= driver.find_element_by_xpath('//*[@id="name"]/div/input')
	showname.clear()
	showname.send_keys('IPL league')
	time.sleep(2)
	# //*[@id="name"]/div[2]
	driver.find_element_by_xpath('//*[@id="name"]/div[2]')
	###wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='IPL league']"))).click()
	###time.sleep(2)
	pyautogui.moveTo(850, 510)
	time.sleep(2)
	pyautogui.click(850, 510)
	#<div id="name" class="sc-jeCdPy jzIkFw"><div label="Show Name" class="sc-ePZHVD jcvQum searchable-section" value=""><p class="dropdown-label">Show Name</p><input type="text" class="sc-bEjcJn iIHRkI" value="Na"></div><div class="sc-drMfKT cxRLap dropdown-option-box"><p class="dropdown-option " role="presentation">Nazar</p><p class="dropdown-option " role="presentation">Nach Baliye</p><p class="dropdown-option " role="presentation">Nach Baliye</p><p class="dropdown-option " role="presentation">Nach Baliye</p><p class="dropdown-option " role="presentation">Nazar</p><p class="dropdown-option " role="presentation">Nazar</p></div></div>
	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#driver.find_element_by_xpath("//div[@id='name']")
	#time.sleep(1)
	#print('search show name')
	#showname= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[1]/div/div[2]/div[2]/div/div[1]/div/div/div/div/div/input')
	#showname.clear()
	#showname.send_keys('Hasya Jatra')
	#time.sleep(2)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Nazar']"))).click()
	#/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[1]/div/div[2]/div[2]/div/div[2]/div/div/div/div/input
	season_name = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[1]/div/div[2]/div[2]/div/div[2]/div/div/div/div/input')
	season_name.clear()
	#time.sleep(3)
	season_name.send_keys('IPL league 13')
	time.sleep(1)
	season_number = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[1]/div/div[2]/div[2]/div/div[3]/div[1]/div/div/div/input')
	season_number.clear()
	season_number.send_keys('10')
	time.sleep(1)
	number_of_episodes = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[1]/div/div[2]/div[2]/div/div[3]/div[2]/div/div/div/input')
	number_of_episodes.clear()
	number_of_episodes.send_keys('10')
	time.sleep(1)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Specials']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Event']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='One-off show']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Series']"))).click()
	time.sleep(1)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Hindi']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Telugu']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Tamil']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Kannada']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Malayalam']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Next']"))).click()
	time.sleep(2)
	''' schedule info '''
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Maa HD']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Maa HD']"))).click()
	# <div label="Program Start Date" class="sc-hmzhuo hXCotp ardp-date-picker"><div><div class="form-input"><label class="floaton">Program Start Date</label><input type="text" theme="light" class="date-picker-trigger-cd1910a2-a5d2-31c1-d6ee-a9eb7b7defe8" readonly="" value="01/09/2020"></div><div class="ardp-calendar-cd1910a2-a5d2-31c1-d6ee-a9eb7b7defe8 calendar calendar-show"><div class="month-header"><span class="prev-month"><i class="sc-bdVaJa lacgtR"><svg width="10" height="20" viewBox="0 0 10 20" color="#FFFFFF" class="sc-bwzfXH gjyUAT"><path d="M6 0 L0 6 L6 12" transform="translate(2, 2)" fill="#FFFFFF" stroke="#999999" stroke-width="2" fill-rule="nonzero"></path></svg></i></span><span class="month-header-text"><span class="month-text">September</span><span class="year-text"> 2020</span></span><span class="next-month"><i class="sc-bdVaJa lacgtR"><svg width="10" height="20" viewBox="0 0 10 20" color="#FFFFFF" class="sc-bwzfXH gjyUAT"><path d="M0 0 L6 6 L0 12" transform="translate(2, 2)" fill="#FFFFFF" stroke="#999999" stroke-width="2" fill-rule="nonzero"></path></svg></i></span></div><div class="week-header"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="weeks"><div class="current"><div class="week"><div class="day other-month"><span> 30</span></div><div class="day other-month"><span> 31</span></div><div class="day selected"><span> 1</span></div><div class="day"><span> 2</span></div><div class="day"><span> 3</span></div><div class="day"><span> 4</span></div><div class="day"><span> 5</span></div></div><div class="week"><div class="day"><span> 6</span></div><div class="day"><span> 7</span></div><div class="day"><span> 8</span></div><div class="day"><span> 9</span></div><div class="day"><span> 10</span></div><div class="day"><span> 11</span></div><div class="day"><span> 12</span></div></div><div class="week"><div class="day"><span> 13</span></div><div class="day"><span> 14</span></div><div class="day"><span> 15</span></div><div class="day"><span> 16</span></div><div class="day"><span> 17</span></div><div class="day"><span> 18</span></div><div class="day"><span> 19</span></div></div><div class="week"><div class="day"><span> 20</span></div><div class="day"><span> 21</span></div><div class="day"><span> 22</span></div><div class="day"><span> 23</span></div><div class="day"><span> 24</span></div><div class="day"><span> 25</span></div><div class="day"><span> 26</span></div></div><div class="week"><div class="day"><span> 27</span></div><div class="day"><span> 28</span></div><div class="day"><span> 29</span></div><div class="day"><span> 30</span></div><div class="day other-month"><span> 1</span></div><div class="day other-month"><span> 2</span></div><div class="day other-month"><span> 3</span></div></div></div><div class="other"><div class="week"><div class="day other-month"><span> 30</span></div><div class="day other-month"><span> 31</span></div><div class="day selected"><span> 1</span></div><div class="day"><span> 2</span></div><div class="day"><span> 3</span></div><div class="day"><span> 4</span></div><div class="day"><span> 5</span></div></div><div class="week"><div class="day"><span> 6</span></div><div class="day"><span> 7</span></div><div class="day"><span> 8</span></div><div class="day"><span> 9</span></div><div class="day"><span> 10</span></div><div class="day"><span> 11</span></div><div class="day"><span> 12</span></div></div><div class="week"><div class="day"><span> 13</span></div><div class="day"><span> 14</span></div><div class="day"><span> 15</span></div><div class="day"><span> 16</span></div><div class="day"><span> 17</span></div><div class="day"><span> 18</span></div><div class="day"><span> 19</span></div></div><div class="week"><div class="day"><span> 20</span></div><div class="day"><span> 21</span></div><div class="day"><span> 22</span></div><div class="day"><span> 23</span></div><div class="day"><span> 24</span></div><div class="day"><span> 25</span></div><div class="day"><span> 26</span></div></div><div class="week"><div class="day"><span> 27</span></div><div class="day"><span> 28</span></div><div class="day"><span> 29</span></div><div class="day"><span> 30</span></div><div class="day other-month"><span> 1</span></div><div class="day other-month"><span> 2</span></div><div class="day other-month"><span> 3</span></div></div></div></div></div></div></div>
	driver.find_element_by_xpath("//div[@class='sc-hmzhuo hXCotp ardp-date-picker']").click()
	logger_season.info('program start date clicked')
	time.sleep(wait_time)
	month_header= driver.find_element_by_xpath("//div[@class='month-header']")
	#time.sleep(1)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='September']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='2020']"))).click()
	logger_season.info('month header selected')
	week_header= driver.find_element_by_xpath("//div[@class='week-header']")
	#time.sleep(1)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Thu']"))).click()
	logger_season.info('week header selected')
	weeks= driver.find_element_by_xpath("//div[@class='weeks']")
	#time.sleep(1)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='3']"))).click()
	logger_season.info('weeks selected')
	#time.sleep(2)
	#driver.find_element_by_xpath("//div[@class='sc-jVODtj gKQkJS']")
	tx_time= driver.find_element_by_xpath("//div[@class='picker-holder']")
	hour_box= driver.find_element_by_xpath("//div[@class='hour-box']")
	for hour_data in range(6):
		up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	
	#up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#time.sleep(wait_time)
	logger_season.info('Hour selected')	
	seperator_box= driver.find_element_by_xpath("//div[@class='separator-box']")
	time.sleep(wait_time)
	#tx_time_minute= driver.find_element_by_xpath("//div[@class='picker-holder']")
	#minute_box= driver.find_element_by_xpath("//div[@class='minute-box']")
	for minute_data in range(8):
		up_arrow2= driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/div[1]/div[2]/div/div/div[2]/div[3]/div[1]").click()
	#<div class="meridiem-box"><div>pm</div></div>
	#meridiem_box= driver.find_element_by_xpath("//div[@class='meridiem-box']")
	#time.sleep(1)	
	#wait(driver, 2).until(EC.element_to_be_clickable((By.XPATH, "//div[text()='am']"))).click()  # converted into pm
	time.sleep(wait_time)
	#print('meridiem-box selected')
	#time.sleep(2) 
	#<div class="sc-jeCdPy jzIkFw"><div class="sc-ePZHVD hUgaId searchable-section" style="cursor: text;"><p class="dropdown-label"></p><input type="text" class="sc-bEjcJn gONHtD" value=""></div></div>
	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#time.sleep(1)
	##print('1')
	#tx_schedule= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/table/tr[1]/td[2]/div/div/input')
	#tx_schedule.click()
	##print('2')
	#time.sleep(wait_time)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='30 mins']"))).click()
	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#tx_schedule= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[1]/div/div[2]/div/div/div/table/tr[2]/td[2]/div/div/input')
	#tx_schedule.click()
	#time.sleep(wait_time)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='20 mins']"))).click()
	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#tx_schedule= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[1]/div/div[2]/div/div/div/table/tr[3]/td[2]/div/div/input')
	#tx_schedule.click()
	#time.sleep(wait_time)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='10 mins']"))).click()
	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#tx_schedule= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[1]/div/div[2]/div/div/div/table/tr[4]/td[2]/div/div/input')
	#tx_schedule.click()
	#time.sleep(wait_time)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='15 mins']"))).click()
	#driver.find_element_by_xpath("//div[@class='sc-jeCdPy jzIkFw']")
	#tx_schedule= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[1]/div/div[2]/div/div/div/table/tr[5]/td[2]/div/div/input')
	#tx_schedule.click()
	#time.sleep(wait_time)
	#wait(driver, 15).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='60 mins']"))).click()
	#row_div=wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, ".//span[@class = 'tab-title']")))
	#row_div.click()
	#driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[1]/input").click()
	#print('program start date clicked')
	#month_header= driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[2]/div[1]")
	#print('month')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[2]/div[1]/span[2]/span[1]').click()
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[2]/div[1]/span[2]/span[2]').click()
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[2]/div[2]')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[2]/div[2]/span[4]').click()
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[2]/div[3]/div[1]/div[1]')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[1]/div/div/div/div[2]/div[3]/div[1]/div[1]/div[4]/span').click()
	##time.sleep(6)
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]/div[1]')
	#for hour_button in range(4):
	#	driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]/div[1]/div[1]').click()
	#print('Hour selected')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]/div[2]')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]/div[3]')
	#for minute_button in range(5): 
	#	driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/div[2]/div/div/div[2]/div[3]/div[1]').click()
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/table/tr[1]/td[2]/div')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/table/tr[1]/td[2]/div/div/input').click()
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/table/tr[1]/td[2]/div/div/p[2]').click()
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/table/tr[2]/td[2]/div')
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/table/tr[2]/td[2]/div/div/input').click()
	#driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/table/tr[2]/td[2]/div/div/p[2]').click()
	#driver.save_screenshot("test9Oct2019_3.png")
	#time.sleep(3)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='NEXT']"))).click()
	time.sleep(2)
	''' OTT info '''
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Hotstar']"))).click()
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Youtube']"))).click()
	#hotstar_show_name = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[1]/div/div/div/div/input')
	#hotstar_show_name.clear()
	#hotstar_show_name.send_keys('Hava ka zoka')
	#hotstar_show_ID = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[2]/div[1]/div/div/div/input')
	#hotstar_show_ID.clear()
	#hotstar_show_ID.send_keys('1001')
	#hotstar_season_ID = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[2]/div[2]/div/div/div/input')
	#hotstar_season_ID.clear()
	#hotstar_season_ID.send_keys('2001')
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Premium']"))).click()
	#time.sleep(1)
	##<div class="label-text">First Publish Time</div>
	#driver.find_element_by_xpath("//div[@class='row-div']")
	#tx_time= driver.find_element_by_xpath("//div[@class='picker-holder']")
	#hour_box= driver.find_element_by_xpath("//div[@class='hour-box']")
	#up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#time.sleep(wait_time)
	#minute_box= driver.find_element_by_xpath("//div[@class='minute-box']")
	#up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	#meridiem_box= driver.find_element_by_xpath("//div[@class='meridiem-box']")
	#wait(driver, 2).until(EC.element_to_be_clickable((By.XPATH, "//div[text()='pm']"))).click()
	#time.sleep(wait_time)
	#/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[2]/div[1]/div/div/div/input
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Youtube']"))).click()
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Hotstar']"))).click()
	#time.sleep(wait_time)
	#driver.close()
	#driver.quit()
	#hotstar_first_publish_datediff = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[5]/div[1]/div/div/div/input')
	#hotstar_first_publish_datediff.clear()
	#hotstar_first_publish_datediff.send_keys('1')
	#hotstar_second_publish_datediff = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[5]/div[2]/div/div/div/input')
	#hotstar_second_publish_datediff.clear()
	#hotstar_second_publish_datediff.send_keys('1')
	##/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[6]/div[1]/div/div/div/input
	#hotstar_season_no=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[6]/div[1]/div/div/div/input')
	#hotstar_season_no.clear()
	#hotstar_season_no.send_keys('1')
	#hotstar_series_no=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[6]/div[2]/div/div/div/input')
	#hotstar_series_no.clear()
	#hotstar_series_no.send_keys('1')
	#hotstar_category_ID=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[7]/div[1]/div/div/div/input')
	#hotstar_category_ID.clear()
	#hotstar_category_ID.send_keys('100')
	#hotstar_productio_house=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[7]/div[2]/div/div/div/input')
	#hotstar_productio_house.clear()
	#hotstar_productio_house.send_keys('Endemol')
	#hotstar_dis_s3path=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[8]/div[1]/div/div/div/input')
	#hotstar_dis_s3path.clear()
	#hotstar_dis_s3path.send_keys('https://www.google.com')
	#/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[8]/div[2]/div/div/div/input
	#hotstar_dis_duration=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[8]/div[2]/div/div/div/input')
	#hotstar_dis_duration.clear()
	#hotstar_dis_duration.send_keys('30')
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Green']"))).click()
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Yellow']"))).click()
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Red']"))).click()
	#time.sleep(2)
	#youtube_header=wait(driver, 5).until(EC.element_to_be_clickable((By.XPATH, ".//span[@class = 'tab-title']")))
	#youtube_header.click()
	##time.sleep(6)
	#youtube_show_name = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[1]/div/div/div/div/input')
	#youtube_show_name.clear()
	#youtube_show_name.send_keys('Hava ka zoka')
	#youtube_show_ID = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[2]/div[1]/div/div/div/input')
	#youtube_show_ID.clear()
	#youtube_show_ID.send_keys('1001')
	#youtube_season_ID = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[2]/div[2]/div/div/div/input')
	#youtube_season_ID.clear()
	#youtube_season_ID.send_keys('2001')
	#time.sleep(1)
	#publish_type1= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[3]/div/div/div/div[2]/label[2]/span')
	#publish_type1.click()
	#print('SVOD')
	##wait(driver, 5).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='SVOD']"))).click()
	##time.sleep(1)
	##print('SVOD')
	##wait(driver, 5).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Premium']"))).click()
	##time.sleep(1)
	##print('Premium')
	##<div class="label-text">First Publish Time</div>
	##driver.find_element_by_xpath("//div[@class='row-div']")
	##tx_time= driver.find_element_by_xpath("//div[@class='picker-holder']")
	##hour_box= driver.find_element_by_xpath("//div[@class='hour-box']")
	##up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	##up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	##up_arrow= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	##time.sleep(wait_time)
	##minute_box= driver.find_element_by_xpath("//div[@class='minute-box']")
	##up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	##up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	##up_arrow2= driver.find_element_by_xpath("//div[@class='up-arrow']").click()
	##meridiem_box= driver.find_element_by_xpath("//div[@class='meridiem-box']")
	##wait(driver, 2).until(EC.element_to_be_clickable((By.XPATH, "//div[text()='pm']"))).click()
	##time.sleep(wait_time)
	##/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[2]/div[1]/div/div/div/input
	##wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Youtube']"))).click()
	##wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Hotstar']"))).click()
	##time.sleep(wait_time)
	##driver.close()
	##driver.quit()
	#youtube_first_publish_datediff = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[5]/div[1]/div/div/div/input')
	#youtube_first_publish_datediff.clear()
	#youtube_first_publish_datediff.send_keys('1')
	#youtube_second_publish_datediff = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[5]/div[2]/div/div/div/input')
	#youtube_second_publish_datediff.clear()
	#youtube_second_publish_datediff.send_keys('1')
	###/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[6]/div[1]/div/div/div/input
	###time.sleep(4)
	##print('publish date')
	#youtube_season_no=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[6]/div[1]/div/div/div/input')
	#youtube_season_no.clear()
	#youtube_season_no.send_keys('1')
	##time.sleep(4)
	#print('publish season')
	#youtube_series_no=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[6]/div[2]/div/div/div/input')
	#youtube_series_no.clear()
	#youtube_series_no.send_keys('1')
	##time.sleep(4)
	#print('publish series')
	#youtube_category_ID=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[7]/div[1]/div/div/div/input')
	#youtube_category_ID.clear()
	#youtube_category_ID.send_keys('100')
	##time.sleep(4)
	#print('category id')
	#youtube_productio_house=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[7]/div[2]/div/div/div/input')
	#youtube_productio_house.clear()
	#youtube_productio_house.send_keys('Endemol')
	###time.sleep(4)
	#print('production house')
	#youtube_dis_s3path=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[8]/div[1]/div/div/div/input')
	#youtube_dis_s3path.clear()
	#youtube_dis_s3path.send_keys('https://www.google.com')
	##/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[8]/div[2]/div/div/div/input
	#youtube_dis_duration=driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[8]/div[2]/div/div/div/input')
	#youtube_dis_duration.clear()
	#youtube_dis_duration.send_keys('30')
	#parental_rating2= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div[10]/div/div/div/div[2]/label[2]/span')
	#parental_rating2.click()
	#print('yellow')
	#time.sleep(wait_time)
	##time.sleep(12)
	#driver.save_screenshot("test9Oct2019_4.png")
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='NEXT']"))).click()
	#Global Info
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='urban']"))).click()
	time.sleep(1)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='event']"))).click()
	time.sleep(1)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='politics']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='sports']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='assembly']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='investigation']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='positive']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='nris']"))).click()
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='telecom']"))).click()
	time.sleep(1)
	driver.save_screenshot("test9Oct2019_5.png")
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Ingest']"))).click()
	time.sleep(1)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='S&P Review']"))).click()
	time.sleep(1)
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Ingest']"))).click()
	time.sleep(1)
	#short_synopsis = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div/div[2]/div[2]/div/div[1]/div/div/div/div/div[2]/div/div[5]/div/div/div/div/input')
	#short_synopsis.clear()
	#short_synopsis.send_keys('whatttt')
	time.sleep(1)
	#long_synopsis = driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div/div[2]/div[2]/div/div[1]/div/div/div/div/div[2]/div/div[6]/div/div/div/div/input')
	#long_synopsis.clear()
	#long_synopsis.send_keys('Howwww')
	time.sleep(1)
	logger_season.info('short and long synopsis added')
	driver.save_screenshot("ttest9Oct2019_6.png")
	wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Add New Row']"))).click()
	credit1 = driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div/div[2]/div[2]/div/div[1]/div/div/div/div/div[2]/div/div[8]/div/div/div/div/div[2]/table/tr/td[1]/div/div/input')
	credit1.clear()
	credit1.send_keys('Rohit shetti')
	credit2 = driver.find_element_by_xpath('//*[@id="root"]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div/div[2]/div[2]/div/div[1]/div/div/div/div/div[2]/div/div[8]/div/div/div/div/div[2]/table/tr/td[2]/div/div/input')
	#credit2.clear()
	credit2.send_keys('Producer')
	#add_season= driver.find_element_by_xpath('/html/body/div[1]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/div/div[2]/div[2]/div/div[2]/div/div/div/div/button')
	#add_season.click()
	logger_season.info('Season added successfully')
	#logout_icon= driver.find_element_by_xpath("//div[@class='header-profile']")
	#print('1')
	#logout_icon.click()
	#time.sleep(2)
	#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//div[text()='Logout']"))).click()
	#time.sleep(2)
	#print('logout')
	time.sleep(4)
	driver.close()
	driver.quit()

except Exception as e:
	logger_season.error('Failed to connect internet:{}'.format(e))
	driver.close()
	driver.quit()


